/**
 * SOVANN FARM — Task 2-b: brand photography batch ORCHESTRATOR.
 *
 * Generates 39 brand photographs into /home/z/my-project/public/images/.
 *
 * Architecture: this orchestrator holds NO heavy deps (no sharp, no SDK) so it
 * survives native crashes; each image is generated by a short-lived child
 * process `bun run scripts/gen-one.ts <jobIndex>` (z-ai-web-dev-sdk + sharp).
 * A crashed/hung child only loses one image and is retried.
 *
 * - Concurrency: 3 (promise pool over child processes)
 * - Retries: up to 2 per image per pass (3 attempts total); 429 responses get longer backoff
 * - Passes: 1 main pass + up to 2 verification passes for missing/undersized files
 * - Idempotent: already-generated files (>=10KB) are skipped on relaunch
 *
 * Launch: `cd /home/z/my-project && nohup bun run scripts/generate-images.ts > scripts/image-gen.log 2>&1 &`
 * (stdout IS scripts/image-gen.log — single writer, no duplication)
 */
import { execFile } from 'child_process';
import { existsSync, mkdirSync, statSync, writeFileSync } from 'fs';
import path from 'path';

const OUT_DIR = '/home/z/my-project/public/images';
const MIN_BYTES = 10 * 1024; // 10KB undersized threshold
const CHILD_TIMEOUT_MS = 240_000;

const PRODUCT_STYLE =
  'professional food product photography, styled on warm ivory linen with soft window light and gentle shadows, premium minimal editorial composition, photorealistic, high quality';
const PORTRAIT_STYLE =
  'portrait of a Cambodian farmer, natural warm smile, golden hour light, shallow depth of field with farm background, documentary editorial photography, photorealistic, high quality';
const NO_TEXT = 'no text, no watermark, no logo, no brand names in image';

type Job = { name: string; size: string; prompt: string };

const P = (base: string) => `${base}, ${PRODUCT_STYLE}, ${NO_TEXT}`;
const F = (base: string) => `${base}, ${PORTRAIT_STYLE}, ${NO_TEXT}`;
const L = (base: string) => `${base}, ${NO_TEXT}`;

const jobs: Job[] = [
  // ---------- Landscape / editorial (16) ----------
  {
    name: 'hero-rice-fields',
    // NOTE: API rejects 1440x720 (720 not a multiple of 32, error 1214); 1440x704 is the
    // closest valid ultra-wide size (both multiples of 32, <=2^22px).
    size: '1440x704',
    prompt: L(
      'Cinematic wide view of flooded Cambodian rice paddies at sunrise, golden mist over emerald green fields, a lone farmer in conical straw hat walking on a narrow earthen path, sugar palm trees silhouetted on the far horizon, warm golden light, editorial documentary photography, photorealistic, high quality, detailed'
    ),
  },
  {
    name: 'campaign-golden-harvest',
    size: '1344x768',
    prompt: L(
      'Dramatic editorial still life of golden rice stalks and grains arranged on dark forest-green fabric, warm dramatic side lighting, luxury fashion campaign aesthetic, deep shadows, gold and deep green tones, photorealistic, high quality'
    ),
  },
  {
    name: 'story-featured-farmer',
    size: '864x1152',
    prompt: L(
      'Portrait of a middle-aged Cambodian rice farmer standing proudly in a green paddy field at golden hour, warm smile, weathered hands, conical hat in hand, shallow depth of field, documentary editorial photography, warm tones, photorealistic, high quality'
    ),
  },
  {
    name: 'about-landscape',
    size: '1344x768',
    prompt: L(
      'Sweeping Cambodian countryside landscape at dusk, rice fields, scattered sugar palm trees, distant mountains under soft violet and gold sky, calm atmospheric mood, documentary photography, photorealistic, high quality'
    ),
  },
  {
    name: 'about-hands-grain',
    size: '1024x1024',
    prompt: L(
      'Close-up of weathered farmer hands cradling uncooked white jasmine rice grains, grains spilling gently through fingers, warm natural light, shallow depth of field, documentary photography, photorealistic, high quality'
    ),
  },
  {
    name: 'farm-rice-fields',
    size: '1344x768',
    prompt: L(
      'Lush green rice paddy field in Cambodia with neat rows of young rice plants leading to wooden stilt house, morning light, documentary photography, photorealistic, high quality'
    ),
  },
  {
    name: 'farm-pepper-vines',
    size: '1024x1024',
    prompt: L(
      'Rows of Kampot pepper vines climbing living wooden poles on a Cambodian family farm, glossy green leaves, clusters of green peppercorns, dappled sunlight, documentary photography, photorealistic, high quality'
    ),
  },
  {
    name: 'farm-palm-grove',
    size: '1344x768',
    prompt: L(
      'Cambodian sugar palm grove at late afternoon, tall elegant borassus palms against warm sky, red dirt path, farmer with bamboo tapping poles, documentary photography, photorealistic, high quality'
    ),
  },
  {
    name: 'farm-orchard',
    size: '1344x768',
    prompt: L(
      'Cambodian mango orchard with ripe mangoes hanging among dense green leaves, woven baskets beneath trees, soft morning light, documentary photography, photorealistic, high quality'
    ),
  },
  {
    name: 'story-journey-kampot-pepper',
    size: '1344x768',
    prompt: L(
      'Dried black peppercorns being raked on sunlit clay drying terraces in Kampot Cambodia, hands with wooden rake, warm afternoon light, steam of heat rising, documentary photography, photorealistic, high quality'
    ),
  },
  {
    name: 'story-jasmine-rice',
    size: '1344x768',
    prompt: L(
      'Cambodian rice harvest scene, farmers bundling golden sheaves of rice in field, warm sunset backlight, joyful documentary moment, photorealistic, high quality'
    ),
  },
  {
    name: 'story-farmers-behind',
    size: '1344x768',
    prompt: L(
      'Group of Cambodian farmers sharing a meal together in a field after harvest, sitting on woven mats, sharing food, warm community feeling, golden hour, documentary photography, photorealistic'
    ),
  },
  {
    name: 'story-palm-sugar-making',
    size: '1024x1024',
    prompt: L(
      'Traditional Cambodian palm sugar making, clay pots collecting palm sap over wood fire, amber sugar paste boiling in large wok, rustic outdoor kitchen, warm smoke and light, documentary photography, photorealistic'
    ),
  },
  {
    name: 'story-life-mekong',
    size: '1344x768',
    prompt: L(
      'Life along the Mekong river in Cambodia, wooden boats, stilt houses, fishing nets drying, morning mist over wide brown river, lush banks, documentary photography, photorealistic'
    ),
  },
  {
    name: 'story-traditional-farming',
    size: '1024x1024',
    prompt: L(
      'Cambodian farmer transplanting rice seedlings by hand into flooded paddy, bent rows reflected in water, overcast soft light, timeless traditional agriculture, documentary photography, photorealistic'
    ),
  },
  {
    name: 'story-future-agriculture',
    size: '1344x768',
    prompt: L(
      'Misty highland hills of Mondulkiri Cambodia with pine trees and coffee plants in early morning fog, young farmer inspecting coffee cherries, cool green tones, documentary photography, photorealistic'
    ),
  },

  // ---------- Products (17, all 1024x1024) ----------
  { name: 'p-kampot-black-pepper', size: '1024x1024', prompt: P('Small glass jar of glossy black peppercorns on warm ivory linen, scattered peppercorns, fresh green pepper sprig beside') },
  { name: 'p-kampot-white-pepper', size: '1024x1024', prompt: P('Ceramic bowl of white peppercorns on warm ivory linen, minimal premium food photography') },
  { name: 'p-jasmine-rice', size: '1024x1024', prompt: P('Hessian sack of white jasmine rice grains spilling onto warm ivory linen, wooden scoop') },
  { name: 'p-brown-rice', size: '1024x1024', prompt: P('Bowl of brown rice grains with wooden scoop on warm ivory linen') },
  { name: 'p-palm-sugar', size: '1024x1024', prompt: P('Round amber palm sugar cakes wrapped in dried palm leaf on warm ivory linen, rustic premium') },
  { name: 'p-roasted-cashews', size: '1024x1024', prompt: P('Wooden bowl of golden roasted cashews on warm ivory linen, scattered cashews') },
  { name: 'p-dried-mango', size: '1024x1024', prompt: P('Sun-dried mango slices fanned on ceramic plate, fresh mango slice garnish, warm ivory linen') },
  { name: 'p-fresh-mangoes', size: '1024x1024', prompt: P('Two ripe golden Keo Romeat mangoes with leaves on warm ivory linen') },
  { name: 'p-dragon-fruit', size: '1024x1024', prompt: P('Fresh red dragon fruit halved showing white speckled flesh, on warm ivory linen') },
  { name: 'p-fresh-longan', size: '1024x1024', prompt: P('Cluster of fresh longan fruits with leaves in small woven basket, warm ivory linen') },
  { name: 'p-young-coconut', size: '1024x1024', prompt: P('Fresh young green coconuts, one opened with straw, on warm ivory linen') },
  { name: 'p-forest-honey', size: '1024x1024', prompt: P('Glass jar of golden wild honey with wooden honey dipper, honeycomb piece, warm ivory linen') },
  { name: 'p-mondulkiri-coffee', size: '1024x1024', prompt: P('Roasted coffee beans in linen sack with small ceramic cup of black coffee, warm ivory linen') },
  { name: 'p-golden-gift-box', size: '1024x1024', prompt: P('Premium gift box in deep forest green with natural ribbon, opened to show rice, pepper jar, honey jar and palm sugar, styled on warm ivory linen, luxury editorial') },
  { name: 'p-pepper-trio', size: '1024x1024', prompt: P('Three small elegant tins of black, white and red Kampot pepper in a row, warm ivory linen, premium') },
  { name: 'p-coconut-chips', size: '1024x1024', prompt: P('Golden toasted coconut chips in ceramic bowl, fresh coconut piece, warm ivory linen') },
  { name: 'p-farm-box', size: '1024x1024', prompt: P('Wooden crate of fresh Cambodian vegetables, herbs and tropical fruit, warm ivory linen backdrop, farm to table styling') },

  // ---------- Farmer portraits (6, all 864x1152) ----------
  { name: 'farmer-sokha-chea', size: '864x1152', prompt: F('Cambodian man in his fifties, rice farmer, in green paddy field') },
  { name: 'farmer-dara-touch', size: '864x1152', prompt: F('Cambodian man in his forties, pepper farmer, beside pepper vine poles') },
  { name: 'farmer-malis-chen', size: '864x1152', prompt: F('Cambodian woman in her thirties, orchard farmer, holding basket of mangoes in orchard') },
  { name: 'farmer-vireak-pong', size: '864x1152', prompt: F('Cambodian man in his forties, palm sugar artisan, at base of tall sugar palm with tapping equipment') },
  { name: 'farmer-sopheap-try', size: '864x1152', prompt: F('Cambodian woman in her fifties, cashew farmer, with cashew fruits and nuts') },
  { name: 'farmer-rathanak-yim', size: '864x1152', prompt: F('Young Cambodian man in his thirties, coffee farmer, in misty highland coffee plantation') },
];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function log(msg: string) {
  process.stdout.write(`[${new Date().toISOString()}] ${msg}\n`);
}

/** Already generated and big enough? (makes relaunches idempotent) */
function isGood(name: string): boolean {
  const p = path.join(OUT_DIR, `${name}.jpg`);
  return existsSync(p) && statSync(p).size >= MIN_BYTES;
}

/** Run one child generation attempt. Resolves {ok, kb?, error?}. */
function runChild(job: Job, index: number): Promise<{ ok: boolean; kb?: number; error?: string }> {
  return new Promise((resolve) => {
    execFile(
      'bun',
      ['run', 'scripts/gen-one.ts', String(index)],
      { cwd: '/home/z/my-project', timeout: CHILD_TIMEOUT_MS, killSignal: 'SIGKILL', maxBuffer: 8 * 1024 * 1024 },
      (err, stdout, stderr) => {
        if (!err && isGood(job.name)) {
          const kb = Math.round(statSync(path.join(OUT_DIR, `${job.name}.jpg`)).size / 1024);
          resolve({ ok: true, kb });
          return;
        }
        const detail = (stderr || stdout || err?.message || 'unknown error').toString().trim().split('\n').slice(-3).join(' | ');
        resolve({ ok: false, error: detail.slice(0, 300) });
      }
    );
  });
}

/** Generate one image: 1 attempt + up to 2 retries, with 429-aware backoff. */
async function generateOne(job: Job, index: number): Promise<{ ok: boolean; kb?: number; error?: string }> {
  for (let attempt = 1; attempt <= 3; attempt++) {
    const r = await runChild(job, index);
    if (r.ok) return r;
    const rateLimited = /429|Too many requests/i.test(r.error || '');
    if (attempt < 3) {
      const wait = rateLimited ? 15_000 * attempt : 3_000 * attempt;
      log(`retry ${job.name}.jpg (attempt ${attempt}/3 failed: ${r.error}) — waiting ${Math.round(wait / 1000)}s`);
      await sleep(wait);
    } else {
      return { ok: false, error: r.error };
    }
  }
  return { ok: false, error: 'unreachable' };
}

/** Concurrency-limited promise pool. */
async function runPool(items: { job: Job; index: number }[], limit: number, worker: (it: { job: Job; index: number }) => Promise<void>) {
  let i = 0;
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (i < items.length) {
      const idx = i++;
      await worker(items[idx]);
    }
  });
  await Promise.all(runners);
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync('/home/z/my-project/scripts/.jobs.json', JSON.stringify(jobs, null, 2));
  log(`=== SOVANN FARM image generation started: ${jobs.length} jobs, concurrency 3 (isolated child processes) ===`);

  let done = 0;
  const failed: Job[] = [];
  const all = jobs.map((job, index) => ({ job, index }));

  // ---- Pass 1: main run (skips files already generated by a previous run) ----
  await runPool(all, 3, async ({ job, index }) => {
    if (isGood(job.name)) {
      done++;
      log(`[${done}/${jobs.length}] skip ${job.name}.jpg (already exists)`);
      return;
    }
    await sleep((index % 3) * 2000); // slight stagger to soften rate limits
    const r = await generateOne(job, index);
    done++;
    if (r.ok) log(`[${done}/${jobs.length}] ok ${job.name}.jpg (${r.kb}KB)`);
    else {
      log(`[${done}/${jobs.length}] FAIL ${job.name}.jpg (${r.error})`);
      failed.push(job);
    }
  });
  log(`--- pass 1 complete: ${jobs.length - failed.length}/${jobs.length} ok, ${failed.length} failed ---`);

  // ---- Passes 2-3: verification re-attempts for missing/undersized files ----
  for (let pass = 2; pass <= 3 && failed.length > 0; pass++) {
    log(`--- verification pass ${pass}: re-attempting ${failed.length} file(s) ---`);
    const still: Job[] = [];
    await runPool(
      failed.map((job) => ({ job, index: jobs.indexOf(job) })),
      3,
      async ({ job, index }) => {
        if (isGood(job.name)) return;
        const r = await generateOne(job, index);
        if (r.ok) log(`[pass${pass}] ok ${job.name}.jpg (${r.kb}KB)`);
        else {
          log(`[pass${pass}] FAIL ${job.name}.jpg (${r.error})`);
          still.push(job);
        }
      }
    );
    failed.length = 0;
    failed.push(...still);
  }

  // ---- Final verification ----
  log('--- VERIFICATION ---');
  const problems: string[] = [];
  for (const job of jobs) {
    const p = path.join(OUT_DIR, `${job.name}.jpg`);
    if (!existsSync(p)) problems.push(`MISSING ${job.name}.jpg`);
    else {
      const bytes = statSync(p).size;
      if (bytes < MIN_BYTES) problems.push(`UNDERSIZED ${job.name}.jpg (${Math.round(bytes / 1024)}KB)`);
    }
  }
  log(`RESULT: ${jobs.length - problems.length}/${jobs.length} ok, ${problems.length} problem(s)`);
  for (const p of problems) log(p);
  log('=== DONE ===');
  process.exit(problems.length > 0 ? 2 : 0);
}

process.on('unhandledRejection', (e: any) => log(`ORCH_UNHANDLED: ${e?.message || e}`));
process.on('uncaughtException', (e: any) => log(`ORCH_UNCAUGHT: ${e?.message || e}`));

main().catch((e) => {
  log(`FATAL: ${e?.message || e}`);
  process.exit(1);
});
